pipeline:
  build:
    image: golang
    secrets: [ artifactory_password, ARTIFACTORY_USER, ARTIFACTORY_URL, go_repo_key ]
    commands:
    # Download the JFrog CLI 
      - echo $GOPATH
      - go get -u golang.org/x/vgo
      - export vgo=$GOPATH/bin/vgo
      - cd hello
      - curl -fL https://getcli.jfrog.io | sh
      - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD
      - ./jfrog rt c show
      - sed -i 's,go_repo_key,'"$go_repo_key"',g' ../configuration.yml
      - ./jfrog rt go build --no-registry
      - ./jfrog rt go build go
      - ./jfrog rt gp go-local v1.0.0 --build-name=my-build --build-number=1

      


